name: Deploy


on: 
  push:
    branches:
      - main

jobs:
  test:
    name: Deploy
    runs on: ubuntu-latest
    steps: 
      - name: Checkout Repo 
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Deploy code
        run: npm run deploy